image: docker:stable

stages:
- pre-build
- build
- test
- deploy

build-docker:
    services:
    - docker:dind

    before_script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

    stage: pre-build
    script: 
    - docker build -t minha-imagem .
    - docker tag minha-imagem leoalmeida95/minha-imagem:latest
    - docker push leoalmeida95/minha-imagem:latest

build-project:
    services:
    - docker:dind
    - mysql:5.7
    variables:
      MYSQL_USER: devops_dev
      MYSQL_PASSWORD: mestre
      MYSQL_DATABASE: todo_dev
      MYSQL_ROOT_PASSWORD: senha
      SECRET_KEY: 'secret_key'

      DB_NAME: 'todo_dev'
      DB_USER: 'devops_dev'
      DB_PASSWORD: 'mestre'
      DB_PORT: '3306'

    stage: build
    tags: 
    - executor-tarefas
    dependencies: 
    - build-docker
    script: 
    - python manage.py makemigrations
    - python manage.py migrate